name: task_social_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # localization
  easy_localization: 3.0.7
  syncfusion_localizations: 27.1.53
  intl: 0.19.0

  #http
  dio: 5.3.3
  pretty_dio_logger: 1.3.0
  http: 0.13.6

  #state management
  get: 4.6.6
  flutter_bloc: 8.1.3

  #firebase
  firebase_core: 3.2.0
  firebase_messaging: 15.0.3
  #  flutter_fcm: 1.2.5

  #  cache
  get_storage: 2.1.1
  cached_network_image: 3.3.0
  flutter_cache_manager: 3.3.1

  # utils
  flutter_typeahead: 5.2.0
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  video_player: ^2.8.1
  readmore: ^2.2.0
  #  draggable_home: ^1.0.2
  easy_splash_screen: ^1.0.4
  image_cropper: ^4.0.1
  table_calendar: ^3.0.9
  syncfusion_flutter_datepicker:


  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  timeago: ^3.7.0
  intl_phone_field: ^3.2.0
  photo_view: ^0.14.0
  flutter_easyloading: ^3.0.5
  dropdown_textfield: ^1.0.8
  #  dropdown_textfield: ^1.2.0
  flutter_svg: ^2.0.9
  awesome_dialog:
  pin_code_fields: ^8.0.1
  dotted_border: ^2.1.0
  flutter_spinkit: ^5.2.0
  pull_to_refresh: ^2.0.0
  flutter_phoenix: ^1.1.1
  flutter_platform_widgets: ^6.0.2
  devicelocale: ^0.7.0
  regexpattern: ^2.6.0
  typed_data: ^1.3.2
  clipboard: ^0.1.3
  file_picker: ^6.1.1
  eva_icons_flutter: ^3.1.0
  fluttertoast: ^8.2.4
  #  TODO

  dropdown_button2: ^1.7.2

  #animation
  simple_animations: 5.0.2
  flutter_staggered_animations: ^1.1.1

  #  marquee: 2.2.3



#project

  flutter_custom_carousel_slider: ^1.2.0
  animated_conditional_builder:
  flutter_staggered_grid_view: ^0.7.0
  path_provider:
  path:
  sqflite:
  logger:
  flutter_story: ^1.0.1











dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1



flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 24 # android min sdk min:16, default 21



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/locales/
    - assets/images/
    - assets/images/splash/
    - assets/images/home/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Acknowledgement
      fonts:
        - asset: assets/fonts/Acknowledgement/Acknowledgement.otf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf


    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/static/Outfit-Black.ttf
          weight: 900
        - asset: assets/fonts/Outfit/static/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/static/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/static/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/static/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/static/Outfit-thin.ttf
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
          weight: 900


    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf


    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300

    - family: DM_Sans
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DM_Sans/DMSans-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/DM_Sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DM_Sans/DMSans-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/DM_Sans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DM_Sans/DMSans-Italic.ttf
          weight: 400
    - family: arabic_font
      fonts:
        - asset: assets/fonts/Arabic Font/neo-sans-arabic-black.ttf
        - asset: assets/fonts/Arabic Font/neo-sans-arabic-bold.ttf
        - asset: assets/fonts/Arabic Font/neo-sans-arabic-light.ttf
        - asset: assets/fonts/Arabic Font/neo-sans-arabic-ultra.ttf
        - asset: assets/fonts/Arabic Font/neosansarabic.ttf
    - family: english_font
      fonts:
        - asset: assets/fonts/English Font/Lato-100.ttf
        - asset: assets/fonts/English Font/Lato-100italic.ttf
        - asset: assets/fonts/English Font/Lato-300.ttf
        - asset: assets/fonts/English Font/Lato-300italic.ttf
        - asset: assets/fonts/English Font/Lato-700.ttf
        - asset: assets/fonts/English Font/Lato-700italic.ttf
        - asset: assets/fonts/English Font/Lato-900.ttf
        - asset: assets/fonts/English Font/Lato-900italic.ttf
        - asset: assets/fonts/English Font/Lato-Italic.ttf
        - asset: assets/fonts/English Font/Lato-Regular.ttf

